version: '3'
services:
    web-server:
        build:
            context: .
        container_name: web-container
        ports:
            - 3000:3000
        volumes:
            - .:/workspace:cached
            - /workspace/node_modules
        command: /bin/bash -c "cd /workspace && npm install && while true; do sleep 3600; done"
        # command: /bin/bash -c "cd /workspace && while true; do sleep 3600; done"