import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ItemDetailsProvider } from '../context/itemContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function WebsiteviewLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ItemDetailsProvider>{children}</ItemDetailsProvider>;
}
